### ISSUE TITLE
[ISSUE] - Avoid negative values returned by MG API (tires and mileage)

### ISSUE THREAD

**Issue by ghislaingaillot** [ad-ha/mg-saic-ha#131]
### Home Assistant Version

2025.3.1

### MG/SAIC Integration Version

0.9.4

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Since a bunch of days the api is returning some false information which are integrated in data.
Are concerned :

- the mileage (negative values) (-12.8km)
- the tyres pressure (negative values) (-5.12 bar) 

Example:
![Image](https://github.com/user-attachments/assets/8a8b53a2-d5cf-43f1-b2e8-192e988cece4)
![Image](https://github.com/user-attachments/assets/3639f5c1-c90f-4a95-b7b2-f894311fe47d)

Logs:
```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:340
integration: Sensor (documentation, issues)
First occurred: March 10, 2025 at 9:25:10 AM (1 occurrences)
Last logged: March 10, 2025 at 9:25:10 AM

Entity sensor.mg_eh32_x7_mileage from integration mg_saic has state class total_increasing, but its state is negative. Triggered by state -12.8 with last_updated set to 2025-03-10T08:24:17.556676+00:00. Please create a bug report at https://github.com/ad-ha/mg-saic-ha/issues
```

Note the false values are also given as wrong in the official application too.

Is the a way to filtering these values and avoid this to be integrated in Home Assistant entities ?

### Logs

```yaml

```

**Comment by ad-ha** [comment]
Hi,

I did notice this as well. I will have to find sometime to go through the logs and find the pattern from the API in order to add some more generic responses exclusions.

Cheers

**Comment by lordsnipe1** [comment]
I have seen the same issue with mileage and tyre pressures, has happened twice now whilst charging. 

I had set up utility meters for mileage (to track daily/weekly/monthly mileage) and these all spiked after the mileage value returned from the negative value to the correct value.

I've since added template sensor filters for mileage and tyre pressure sensors so the filter sensor becomes unavailable when negative. I've changed my automations and utility meters to use these filtered values.

  - sensor:
    - name: mg4xpower_mileage_filter
      device_class: Distance
      state_class: total_increasing
      unit_of_measurement: km
      state: "{{ states('sensor.mg_mg4_mileage') }}"
      availability: "{{ states('sensor.mg_mg4_mileage')|float(0) > 0 }}"
  - sensor:	  
    - name: mg4xpower_tyre_pressure_front_left_filter
      device_class: Pressure
      state_class: measurement
      unit_of_measurement: psi
      state: "{{ states('sensor.mg_mg4_tyre_pressure_front_left') }}"
      availability: "{{ states('sensor.mg_mg4_tyre_pressure_front_left')|float(0) > 0 }}"
  - sensor:	  
    - name: mg4xpower_tyre_pressure_front_right_filter
      device_class: Pressure
      state_class: measurement
      unit_of_measurement: psi
      state: "{{ states('sensor.mg_mg4_tyre_pressure_front_right') }}"
      availability: "{{ states('sensor.mg_mg4_tyre_pressure_front_right')|float(0) > 0 }}"
  - sensor:	  
    - name: mg4xpower_tyre_pressure_rear_left_filter
      device_class: Pressure
      state_class: measurement
      unit_of_measurement: psi
      state: "{{ states('sensor.mg_mg4_tyre_pressure_rear_left') }}"
      availability: "{{ states('sensor.mg_mg4_tyre_pressure_rear_left')|float(0) > 0 }}"
  - sensor:	  
    - name: mg4xpower_tyre_pressure_rear_right_filter
      device_class: Pressure
      state_class: measurement
      unit_of_measurement: psi
      state: "{{ states('sensor.mg_mg4_tyre_pressure_rear_right') }}"
      availability: "{{ states('sensor.mg_mg4_tyre_pressure_rear_right')|float(0) > 0 }}"

Hopefully it stops my automations and utility meters calculating on the invalid data whilst you work out a way to resolve the issue.

**Comment by ad-ha** [comment]
I believe I got it sorted.

I will do a quick release with the mileage fix.

**Comment by ad-ha** [comment]
Should be solved with 0.9.5

**Comment by ghislaingaillot** [comment]
Thanks a lot  @ad-ha ! I

**Comment by lordsnipe1** [comment]
Thanks @ad-ha for the quick turnaround. Do your changes also resolve tyre pressures going negative?

**Comment by ad-ha** [comment]
@lordsnipe1

Since it seems like those negatives are coming on the same response, yes, it should fix both issues.

Unless someone at MG decides again to throw some more random responses (non-sense to be honest and unacceptable) to mess with the data. 🙄

**Comment by lordsnipe1** [comment]
I'm still seeing negative tyre pressures whilst charging today while on the latest version. My template sensors filtered them out though so I didn't get any alerts from my automations.

![Image](https://github.com/user-attachments/assets/4430d6cc-5b4d-404c-85bd-70151eb32be4)

**Comment by Rossaluss** [comment]
I'm actually seeing this a lot more frequently since the latest update, to be honest. Is anyone else experiencing this as well?

![Image](https://github.com/user-attachments/assets/d12c656d-8d36-4c5a-9774-b039be61db3e)

**Comment by ad-ha** [comment]
Just to be clear, the update has nothing to do with those values. Those come directly from MG API, not an issue from the Integration.

**Comment by Rossaluss** [comment]
Is there any way for the integration to discard negative values if it receives them?

**Comment by ad-ha** [comment]
> Is there any way for the integration to discard negative values if it receives them?

That's what it already does with some of the values received (mileage, temperatures, and many others on charging data), including other generics that are not negative.

I just have to add the tyre's to the check, but did not have the time yet.
